apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  labels:
    app: front
spec:
  securityContext:
    runAsNoRoot: true
    readOnlyRootFileSystem: true
    allowPriviligeEscalation: false
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
    supplementalGroups: [4000]
  replicas: 2
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: users
        image: abdelhak245/microservice-front:1.0
        ports:
        - containerPort: 8081
        env:
        - name: NOTES_ENDPOINT
          value: "http://notes.dev.svc.cluster.local:8080"
        - name: USERS_ENDPOINT
          value: "http://users.dev.svc.cluster.local:8082"
