apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: devops-role
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["deployments"]
  verbs: ["scale"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["view"]
